#ifndef UMS_IOCTL_H
#define UMS_IOCTL_H

#include <linux/ioctl.h>

#define UMS_DEV_NAME		"ums"

#define UMS_IOC_MAGIC		0xF0

#define IOCTL_CREATE_UMS_CTX	_IO(UMS_IOC_MAGIC, 1)
#define IOCTL_CREATE_UMS_CLIST	_IO(UMS_IOC_MAGIC, 2)
#define IOCTL_ENTER_UMS		_IO(UMS_IOC_MAGIC, 3)
#define IOCTL_DEQUEUE_UMS_CLIST	_IO(UMS_IOC_MAGIC, 4)
#define IOCTL_NEXT_UMS_CLIST	_IO(UMS_IOC_MAGIC, 5)
#define IOCTL_EXEC_UMS_CTX	_IO(UMS_IOC_MAGIC, 6)
#define IOCTL_UMS_YIELD		_IO(UMS_IOC_MAGIC, 7)
#define IOCTL_DELETE_UMS_CLIST	_IO(UMS_IOC_MAGIC, 8)
#define IOCTL_DELETE_UMS_CTX	_IO(UMS_IOC_MAGIC, 9)

#endif /* UMS_IOCTL_H */
